"""
Module 02 Telemetry Parameter Registry & Causal Metadata (Phase 3.8 Full Thermodynamic Combustion Update).
SIH26054 — Module 02 Engine Simulator.
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional
from src.module02.models.enums import ParameterCategory, ParameterStatus


@dataclass(frozen=True)
class ParameterDefinition:
    """Complete Parameter Definition, Implementation Status & Causal Metadata Container."""
    parameter_id: str
    display_name: str
    display_unit: str
    canonical_unit: str
    category: ParameterCategory
    status: ParameterStatus
    description: str
    upstream_cause_ids: List[str] = field(default_factory=list)
    downstream_effect_ids: List[str] = field(default_factory=list)
    telemetry_column_name: str = ""


class RegistryError(ValueError):
    """Raised when parameter registry validation fails."""
    pass


class ParameterRegistry:
    """
    Central Registry of all physical, flight, environmental, thermal, lubrication,
    electrical, battery, aircraft dynamics, degradation, turbocharger, gearbox, and metadata parameters for Module 02.
    """

    def __init__(self) -> None:
        self._registry: Dict[str, ParameterDefinition] = {}
        self._populate_default_registry()

    def register(self, param: ParameterDefinition) -> None:
        """Registers a parameter definition into the registry."""
        if param.parameter_id in self._registry:
            raise RegistryError(f"Duplicate parameter_id in registry: {param.parameter_id}")
        self._registry[param.parameter_id] = param

    def get_parameter(self, parameter_id: str) -> ParameterDefinition:
        """Retrieves parameter definition by ID."""
        if parameter_id not in self._registry:
            raise RegistryError(f"Parameter ID not found in registry: {parameter_id}")
        return self._registry[parameter_id]

    def list_all_parameters(self) -> List[ParameterDefinition]:
        """Returns list of all registered parameter definitions."""
        return list(self._registry.values())

    def validate_registry_integrity(self) -> bool:
        """
        Validates completeness, zero duplicate IDs, canonical SI unit presence,
        and causal metadata validity.
        """
        if len(self._registry) == 0:
            raise RegistryError("Registry is empty.")

        param_ids = set(self._registry.keys())

        for param_id, param in self._registry.items():
            if not param.parameter_id:
                raise RegistryError("Parameter definition missing parameter_id.")
            if not param.canonical_unit:
                raise RegistryError(f"Parameter {param_id} missing canonical_unit declaration.")

            # Validate upstream cause IDs exist in registry
            for cause_id in param.upstream_cause_ids:
                if cause_id not in param_ids and not cause_id.startswith("user_"):
                    raise RegistryError(f"Parameter {param_id} references unknown upstream cause ID: {cause_id}")

            # Validate downstream effect IDs exist in registry
            for effect_id in param.downstream_effect_ids:
                if effect_id not in param_ids and not effect_id.startswith("internal_"):
                    raise RegistryError(f"Parameter {param_id} references unknown downstream effect ID: {effect_id}")

        return True

    def _populate_default_registry(self) -> None:
        """Populates all parameters with explicit ParameterStatus declarations."""

        params = [
            # ENVIRONMENT (Phase 2 Implemented / Derived)
            ParameterDefinition(
                parameter_id="altitude",
                display_name="Altitude",
                display_unit="m",
                canonical_unit="METER",
                category=ParameterCategory.ENVIRONMENT,
                status=ParameterStatus.IMPLEMENTED,
                description="UAV flight altitude above sea level",
                upstream_cause_ids=["aircraft_altitude"],
                downstream_effect_ids=["ambient_pressure", "ambient_temperature", "air_density"],
                telemetry_column_name="altitude_m",
            ),
            ParameterDefinition(
                parameter_id="ambient_temperature",
                display_name="Ambient Temperature",
                display_unit="°C",
                canonical_unit="KELVIN",
                category=ParameterCategory.ENVIRONMENT,
                status=ParameterStatus.IMPLEMENTED,
                description="Ambient air temperature",
                upstream_cause_ids=["altitude"],
                downstream_effect_ids=["air_density", "cht", "egt", "oil_temperature"],
                telemetry_column_name="ambient_temp_k",
            ),
            ParameterDefinition(
                parameter_id="ambient_pressure",
                display_name="Ambient Pressure",
                display_unit="bar",
                canonical_unit="PASCAL",
                category=ParameterCategory.ENVIRONMENT,
                status=ParameterStatus.DERIVED,
                description="Atmospheric static pressure",
                upstream_cause_ids=["altitude"],
                downstream_effect_ids=["air_density", "manifold_pressure", "compressor_pressure_ratio"],
                telemetry_column_name="ambient_pressure_pa",
            ),
            ParameterDefinition(
                parameter_id="air_density",
                display_name="Moist Air Density",
                display_unit="kg/m³",
                canonical_unit="KG_PER_M3",
                category=ParameterCategory.ENVIRONMENT,
                status=ParameterStatus.DERIVED,
                description="Moist air mass density",
                upstream_cause_ids=["ambient_pressure", "ambient_temperature", "relative_humidity"],
                downstream_effect_ids=["air_mass_flow", "drag_force", "propeller_thrust", "propeller_torque"],
                telemetry_column_name="air_density_kg_m3",
            ),
            ParameterDefinition(
                parameter_id="relative_humidity",
                display_name="Relative Humidity",
                display_unit="%",
                canonical_unit="PERCENT",
                category=ParameterCategory.ENVIRONMENT,
                status=ParameterStatus.IMPLEMENTED,
                description="Ambient moisture percentage",
                upstream_cause_ids=[],
                downstream_effect_ids=["air_density", "air_fuel_ratio"],
                telemetry_column_name="relative_humidity_percent",
            ),
            ParameterDefinition(
                parameter_id="wind_speed",
                display_name="Wind Speed",
                display_unit="m/s",
                canonical_unit="M_PER_SEC",
                category=ParameterCategory.ENVIRONMENT,
                status=ParameterStatus.IMPLEMENTED,
                description="Ambient wind speed vector magnitude",
                upstream_cause_ids=[],
                downstream_effect_ids=["airspeed"],
                telemetry_column_name="wind_speed_m_s",
            ),

            # AIRCRAFT & 3-DOF LONGITUDINAL FLIGHT DYNAMICS (Phase 3.7 & Phase 3.8 Implemented / Derived)
            ParameterDefinition(
                parameter_id="aircraft_velocity",
                display_name="Aircraft True Airspeed",
                display_unit="m/s",
                canonical_unit="M_PER_SEC",
                category=ParameterCategory.FLIGHT,
                status=ParameterStatus.IMPLEMENTED,
                description="3-DOF Aircraft true forward velocity V",
                upstream_cause_ids=["longitudinal_acceleration"],
                downstream_effect_ids=["drag_force", "aircraft_x_position", "aircraft_altitude"],
                telemetry_column_name="aircraft_velocity_m_s",
            ),
            ParameterDefinition(
                parameter_id="aircraft_altitude",
                display_name="Aircraft Altitude",
                display_unit="m",
                canonical_unit="METER",
                category=ParameterCategory.FLIGHT,
                status=ParameterStatus.IMPLEMENTED,
                description="3-DOF Aircraft geometric altitude h",
                upstream_cause_ids=["aircraft_velocity", "flight_path_angle"],
                downstream_effect_ids=["altitude", "air_density"],
                telemetry_column_name="aircraft_altitude_m",
            ),
            ParameterDefinition(
                parameter_id="aircraft_x_position",
                display_name="Horizontal Distance",
                display_unit="m",
                canonical_unit="METER",
                category=ParameterCategory.FLIGHT,
                status=ParameterStatus.IMPLEMENTED,
                description="3-DOF Aircraft horizontal position x",
                upstream_cause_ids=["aircraft_velocity", "flight_path_angle"],
                downstream_effect_ids=[],
                telemetry_column_name="aircraft_x_m",
            ),
            ParameterDefinition(
                parameter_id="flight_path_angle",
                display_name="Flight Path Angle",
                display_unit="rad",
                canonical_unit="RADIAN",
                category=ParameterCategory.FLIGHT,
                status=ParameterStatus.IMPLEMENTED,
                description="3-DOF Aircraft climb/descent flight path angle gamma",
                upstream_cause_ids=[],
                downstream_effect_ids=["longitudinal_acceleration", "aircraft_altitude", "aircraft_x_position"],
                telemetry_column_name="flight_path_angle_rad",
            ),
            ParameterDefinition(
                parameter_id="drag_force",
                display_name="Aerodynamic Drag Force",
                display_unit="N",
                canonical_unit="NEWTON",
                category=ParameterCategory.FLIGHT,
                status=ParameterStatus.DERIVED,
                description="3-DOF Total aircraft aerodynamic drag force D = 0.5 * rho * V^2 * S * CD",
                upstream_cause_ids=["aircraft_velocity", "air_density"],
                downstream_effect_ids=["longitudinal_acceleration"],
                telemetry_column_name="drag_force_n",
            ),
            ParameterDefinition(
                parameter_id="weight_force",
                display_name="Aircraft Weight Force",
                display_unit="N",
                canonical_unit="NEWTON",
                category=ParameterCategory.FLIGHT,
                status=ParameterStatus.DERIVED,
                description="Aircraft gravitational weight force W = m_ac * g",
                upstream_cause_ids=["aircraft_mass"],
                downstream_effect_ids=["longitudinal_acceleration"],
                telemetry_column_name="weight_force_n",
            ),
            ParameterDefinition(
                parameter_id="total_thrust",
                display_name="Total Propulsive Thrust",
                display_unit="N",
                canonical_unit="NEWTON",
                category=ParameterCategory.FLIGHT,
                status=ParameterStatus.DERIVED,
                description="Combined propulsive thrust F_thrust,total = F_thrust,eng1 + F_thrust,eng2",
                upstream_cause_ids=["propeller_thrust"],
                downstream_effect_ids=["longitudinal_acceleration"],
                telemetry_column_name="total_thrust_n",
            ),
            ParameterDefinition(
                parameter_id="longitudinal_acceleration",
                display_name="Longitudinal Acceleration",
                display_unit="m/s²",
                canonical_unit="M_PER_SEC2",
                category=ParameterCategory.FLIGHT,
                status=ParameterStatus.DERIVED,
                description="3-DOF Aircraft longitudinal acceleration dV/dt",
                upstream_cause_ids=["total_thrust", "drag_force", "weight_force", "flight_path_angle"],
                downstream_effect_ids=["aircraft_velocity"],
                telemetry_column_name="longitudinal_acceleration_m_s2",
            ),
            ParameterDefinition(
                parameter_id="airspeed",
                display_name="Airspeed",
                display_unit="m/s",
                canonical_unit="M_PER_SEC",
                category=ParameterCategory.FLIGHT,
                status=ParameterStatus.IMPLEMENTED,
                description="Relative forward airspeed V_inf",
                upstream_cause_ids=["aircraft_velocity", "wind_speed"],
                downstream_effect_ids=["vertical_speed", "cooling_heat_rejection"],
                telemetry_column_name="airspeed_m_s",
            ),
            ParameterDefinition(
                parameter_id="vertical_speed",
                display_name="Vertical Speed",
                display_unit="m/s",
                canonical_unit="M_PER_SEC",
                category=ParameterCategory.FLIGHT,
                status=ParameterStatus.DERIVED,
                description="Rate of climb V_z",
                upstream_cause_ids=["aircraft_velocity", "flight_path_angle"],
                downstream_effect_ids=["altitude"],
                telemetry_column_name="vertical_speed_m_s",
            ),
            ParameterDefinition(
                parameter_id="aircraft_mass",
                display_name="Aircraft Mass",
                display_unit="kg",
                canonical_unit="KILOGRAM",
                category=ParameterCategory.FLIGHT,
                status=ParameterStatus.IMPLEMENTED,
                description="Total aircraft mass m_ac",
                upstream_cause_ids=["fuel_mass_flow"],
                downstream_effect_ids=["weight_force", "longitudinal_acceleration"],
                telemetry_column_name="aircraft_mass_kg",
            ),
            ParameterDefinition(
                parameter_id="aerodynamic_drag",
                display_name="Aerodynamic Drag",
                display_unit="N",
                canonical_unit="NEWTON",
                category=ParameterCategory.FLIGHT,
                status=ParameterStatus.DERIVED,
                description="Total aircraft drag force F_drag",
                upstream_cause_ids=["drag_force"],
                downstream_effect_ids=[],
                telemetry_column_name="aerodynamic_drag_n",
            ),
            ParameterDefinition(
                parameter_id="propeller_thrust",
                display_name="Propeller Thrust",
                display_unit="N",
                canonical_unit="NEWTON",
                category=ParameterCategory.FLIGHT,
                status=ParameterStatus.DERIVED,
                description="Propeller propulsive thrust F_thrust",
                upstream_cause_ids=["propeller_rpm", "air_density"],
                downstream_effect_ids=["total_thrust"],
                telemetry_column_name="propeller_thrust_n",
            ),

            # TURBOCHARGER & DYNAMIC CLOSURE (Phase 3.4 & Phase 3.8 Implemented / Derived)
            ParameterDefinition(
                parameter_id="turbo_speed",
                display_name="Turbocharger Speed",
                display_unit="RPM",
                canonical_unit="RAD_PER_SEC",
                category=ParameterCategory.TURBOCHARGER,
                status=ParameterStatus.IMPLEMENTED,
                description="Turbocharger shaft rotational speed N_turbo",
                upstream_cause_ids=["turbine_torque", "compressor_torque", "turbo_friction_torque"],
                downstream_effect_ids=["compressor_pressure_ratio", "turbo_omega"],
                telemetry_column_name="turbo_speed_rpm",
            ),
            ParameterDefinition(
                parameter_id="turbo_shaft_speed",
                display_name="Turbo Shaft Speed",
                display_unit="RPM",
                canonical_unit="RAD_PER_SEC",
                category=ParameterCategory.TURBOCHARGER,
                status=ParameterStatus.IMPLEMENTED,
                description="Turbocharger shaft speed N_turbo",
                upstream_cause_ids=["turbo_speed"],
                downstream_effect_ids=["compressor_power"],
                telemetry_column_name="turbo_shaft_speed_rpm",
            ),
            ParameterDefinition(
                parameter_id="turbo_omega",
                display_name="Turbo Angular Velocity",
                display_unit="rad/s",
                canonical_unit="RAD_PER_SEC",
                category=ParameterCategory.TURBOCHARGER,
                status=ParameterStatus.DERIVED,
                description="Turbocharger shaft angular velocity omega_turbo",
                upstream_cause_ids=["turbo_speed"],
                downstream_effect_ids=["compressor_torque", "turbo_friction_torque"],
                telemetry_column_name="turbo_omega_rad_per_sec",
            ),
            ParameterDefinition(
                parameter_id="turbine_torque",
                display_name="Turbine Driving Torque",
                display_unit="N·m",
                canonical_unit="NEWTON_METER",
                category=ParameterCategory.TURBOCHARGER,
                status=ParameterStatus.DERIVED,
                description="Turbine aerodynamic shaft driving torque tau_turbine",
                upstream_cause_ids=["turbine_power", "turbo_omega"],
                downstream_effect_ids=["turbo_speed"],
                telemetry_column_name="turbine_torque_n_m",
            ),
            ParameterDefinition(
                parameter_id="compressor_torque",
                display_name="Compressor Load Torque",
                display_unit="N·m",
                canonical_unit="NEWTON_METER",
                category=ParameterCategory.TURBOCHARGER,
                status=ParameterStatus.DERIVED,
                description="Compressor aerodynamic shaft load torque tau_compressor",
                upstream_cause_ids=["compressor_power", "turbo_omega"],
                downstream_effect_ids=["turbo_speed"],
                telemetry_column_name="compressor_torque_n_m",
            ),
            ParameterDefinition(
                parameter_id="turbo_shaft_torque",
                display_name="Turbo Shaft Net Torque",
                display_unit="N·m",
                canonical_unit="NEWTON_METER",
                category=ParameterCategory.TURBOCHARGER,
                status=ParameterStatus.DERIVED,
                description="Net torque acting on turbocharger shaft J_turbo * domega/dt",
                upstream_cause_ids=["turbine_torque", "compressor_torque"],
                downstream_effect_ids=["turbo_speed"],
                telemetry_column_name="turbo_shaft_torque_n_m",
            ),
            ParameterDefinition(
                parameter_id="turbo_friction_torque",
                display_name="Turbo Friction Torque",
                display_unit="N·m",
                canonical_unit="NEWTON_METER",
                category=ParameterCategory.TURBOCHARGER,
                status=ParameterStatus.DERIVED,
                description="Turbo shaft mechanical friction torque tau_friction",
                upstream_cause_ids=["turbo_omega"],
                downstream_effect_ids=["turbo_speed"],
                telemetry_column_name="turbo_friction_torque_n_m",
            ),
            ParameterDefinition(
                parameter_id="turbine_power",
                display_name="Turbine Output Power",
                display_unit="W",
                canonical_unit="WATT",
                category=ParameterCategory.TURBOCHARGER,
                status=ParameterStatus.DERIVED,
                description="Turbine aerodynamic power extraction P_turbine",
                upstream_cause_ids=["exhaust_energy_available"],
                downstream_effect_ids=["turbine_torque"],
                telemetry_column_name="turbine_power_w",
            ),
            ParameterDefinition(
                parameter_id="compressor_power",
                display_name="Compressor Work Power",
                display_unit="W",
                canonical_unit="WATT",
                category=ParameterCategory.TURBOCHARGER,
                status=ParameterStatus.DERIVED,
                description="Compressor thermodynamic power requirement P_compressor",
                upstream_cause_ids=["air_mass_flow", "compressor_outlet_temperature"],
                downstream_effect_ids=["compressor_torque"],
                telemetry_column_name="compressor_power_w",
            ),
            ParameterDefinition(
                parameter_id="exhaust_energy_available",
                display_name="Exhaust Energy Rate",
                display_unit="W",
                canonical_unit="WATT",
                category=ParameterCategory.TURBOCHARGER,
                status=ParameterStatus.DERIVED,
                description="Total exhaust thermal energy rate available to turbine E_dot_exh",
                upstream_cause_ids=["fuel_mass_flow", "air_mass_flow"],
                downstream_effect_ids=["turbine_power", "egt"],
                telemetry_column_name="exhaust_energy_rate_w",
            ),
            ParameterDefinition(
                parameter_id="compressor_pressure_ratio",
                display_name="Compressor Pressure Ratio",
                display_unit="Ratio",
                canonical_unit="RATIO",
                category=ParameterCategory.TURBOCHARGER,
                status=ParameterStatus.DERIVED,
                description="Compressor pressure ratio Pi_c = MAP / P_amb",
                upstream_cause_ids=["turbo_speed", "ambient_pressure"],
                downstream_effect_ids=["manifold_pressure", "compressor_outlet_temperature"],
                telemetry_column_name="compressor_pressure_ratio",
            ),
            ParameterDefinition(
                parameter_id="compressor_outlet_temperature",
                display_name="Compressor Outlet Temperature",
                display_unit="°C",
                canonical_unit="KELVIN",
                category=ParameterCategory.TURBOCHARGER,
                status=ParameterStatus.DERIVED,
                description="Compressor discharge air temperature T_comp_out",
                upstream_cause_ids=["compressor_pressure_ratio", "ambient_temperature"],
                downstream_effect_ids=["compressor_power"],
                telemetry_column_name="compressor_outlet_temp_k",
            ),
            ParameterDefinition(
                parameter_id="boost_pressure",
                display_name="Boost Pressure",
                display_unit="bar",
                canonical_unit="PASCAL",
                category=ParameterCategory.TURBOCHARGER,
                status=ParameterStatus.DERIVED,
                description="Compressor gauge boost pressure",
                upstream_cause_ids=["manifold_pressure", "ambient_pressure"],
                downstream_effect_ids=[],
                telemetry_column_name="boost_pressure_pa",
            ),

            # GEARBOX & PROPELLER
            ParameterDefinition(
                parameter_id="gearbox_ratio",
                display_name="Gearbox Speed Ratio",
                display_unit="Ratio",
                canonical_unit="RATIO",
                category=ParameterCategory.GEARBOX,
                status=ParameterStatus.CONFIGURED,
                description="Engine to propeller speed ratio N_prop / N_engine",
                upstream_cause_ids=[],
                downstream_effect_ids=["propeller_rpm", "engine_load_torque"],
                telemetry_column_name="gearbox_ratio",
            ),
            ParameterDefinition(
                parameter_id="propeller_speed_ratio",
                display_name="Propeller Speed Ratio",
                display_unit="Ratio",
                canonical_unit="RATIO",
                category=ParameterCategory.GEARBOX,
                status=ParameterStatus.CONFIGURED,
                description="Propeller speed ratio N_prop / N_engine",
                upstream_cause_ids=[],
                downstream_effect_ids=["propeller_rpm"],
                telemetry_column_name="propeller_speed_ratio",
            ),
            ParameterDefinition(
                parameter_id="gearbox_efficiency",
                display_name="Gearbox Efficiency",
                display_unit="%",
                canonical_unit="RATIO",
                category=ParameterCategory.GEARBOX,
                status=ParameterStatus.CONFIGURED,
                description="Gearbox transmission efficiency eta_gb",
                upstream_cause_ids=[],
                downstream_effect_ids=["engine_load_torque"],
                telemetry_column_name="gearbox_efficiency",
            ),
            ParameterDefinition(
                parameter_id="engine_load_torque",
                display_name="Reflected Engine Load Torque",
                display_unit="N·m",
                canonical_unit="NEWTON_METER",
                category=ParameterCategory.GEARBOX,
                status=ParameterStatus.DERIVED,
                description="Propeller aerodynamic load reflected to engine crankshaft T_engine_load",
                upstream_cause_ids=["propeller_torque", "gearbox_ratio", "gearbox_efficiency"],
                downstream_effect_ids=["engine_rpm"],
                telemetry_column_name="engine_load_torque_n_m",
            ),
            ParameterDefinition(
                parameter_id="propeller_rpm",
                display_name="Propeller Speed",
                display_unit="RPM",
                canonical_unit="RAD_PER_SEC",
                category=ParameterCategory.FLIGHT,
                status=ParameterStatus.IMPLEMENTED,
                description="Propeller shaft rotational speed N_prop",
                upstream_cause_ids=["engine_rpm", "gearbox_ratio"],
                downstream_effect_ids=["propeller_torque", "propeller_thrust", "vibration_rms"],
                telemetry_column_name="propeller_rpm",
            ),
            ParameterDefinition(
                parameter_id="propeller_torque",
                display_name="Propeller Aerodynamic Torque",
                display_unit="N·m",
                canonical_unit="NEWTON_METER",
                category=ParameterCategory.FLIGHT,
                status=ParameterStatus.DERIVED,
                description="Propeller aerodynamic load torque T_prop",
                upstream_cause_ids=["propeller_rpm", "air_density"],
                downstream_effect_ids=["engine_load_torque"],
                telemetry_column_name="propeller_torque_n_m",
            ),

            # FUEL SYSTEM & THERMODYNAMICS (Phase 3.8 Implemented / Derived)
            ParameterDefinition(
                parameter_id="fuel_mass_flow",
                display_name="Fuel Mass Flow Rate",
                display_unit="kg/h",
                canonical_unit="KG_PER_SEC",
                category=ParameterCategory.ENGINE_DYNAMICS,
                status=ParameterStatus.IMPLEMENTED,
                description="Metered fuel delivery mass flow m_dot_fuel",
                upstream_cause_ids=["throttle", "thermal_derating", "injector_degradation"],
                downstream_effect_ids=["air_fuel_ratio", "heat_release_rate", "aircraft_mass"],
                telemetry_column_name="fuel_mass_flow_kg_s",
            ),
            ParameterDefinition(
                parameter_id="fuel_mass_flow_rate",
                display_name="Fuel Mass Flow Rate (h)",
                display_unit="kg/h",
                canonical_unit="KG_PER_SEC",
                category=ParameterCategory.ENGINE_DYNAMICS,
                status=ParameterStatus.IMPLEMENTED,
                description="Metered fuel flow rate in kg/h",
                upstream_cause_ids=["fuel_mass_flow"],
                downstream_effect_ids=[],
                telemetry_column_name="fuel_flow_kg_h",
            ),
            ParameterDefinition(
                parameter_id="fuel_energy_rate",
                display_name="Fuel Energy Input Rate",
                display_unit="W",
                canonical_unit="WATT",
                category=ParameterCategory.COMBUSTION,
                status=ParameterStatus.DERIVED,
                description="Chemical fuel energy input rate P_fuel = m_dot_fuel * LHV",
                upstream_cause_ids=["fuel_mass_flow"],
                downstream_effect_ids=["heat_release_rate"],
                telemetry_column_name="fuel_energy_rate_w",
            ),
            ParameterDefinition(
                parameter_id="air_fuel_ratio",
                display_name="Air-Fuel Ratio",
                display_unit="Ratio",
                canonical_unit="RATIO",
                category=ParameterCategory.COMBUSTION,
                status=ParameterStatus.DERIVED,
                description="Combustion Air-Fuel Ratio (AFR)",
                upstream_cause_ids=["air_mass_flow", "fuel_mass_flow"],
                downstream_effect_ids=["equivalence_ratio", "combustion_efficiency"],
                telemetry_column_name="air_fuel_ratio",
            ),
            ParameterDefinition(
                parameter_id="equivalence_ratio",
                display_name="Equivalence Ratio",
                display_unit="phi",
                canonical_unit="RATIO",
                category=ParameterCategory.COMBUSTION,
                status=ParameterStatus.DERIVED,
                description="Fuel-Air Equivalence Ratio phi = AFR_stoich / AFR_actual",
                upstream_cause_ids=["air_fuel_ratio"],
                downstream_effect_ids=["combustion_efficiency", "egt"],
                telemetry_column_name="equivalence_ratio",
            ),
            ParameterDefinition(
                parameter_id="combustion_efficiency",
                display_name="Combustion Efficiency",
                display_unit="%",
                canonical_unit="RATIO",
                category=ParameterCategory.COMBUSTION,
                status=ParameterStatus.DERIVED,
                description="Bounded combustion efficiency eta_comb",
                upstream_cause_ids=["equivalence_ratio", "ring_degradation", "injector_degradation"],
                downstream_effect_ids=["heat_release_rate"],
                telemetry_column_name="combustion_efficiency_ratio",
            ),
            ParameterDefinition(
                parameter_id="heat_release_rate",
                display_name="Combustion Heat Release Rate",
                display_unit="W",
                canonical_unit="WATT",
                category=ParameterCategory.COMBUSTION,
                status=ParameterStatus.DERIVED,
                description="Total combustion heat release rate P_heat = P_fuel * eta_comb",
                upstream_cause_ids=["fuel_energy_rate", "combustion_efficiency"],
                downstream_effect_ids=["indicated_power", "exhaust_temperature", "cht"],
                telemetry_column_name="heat_release_w",
            ),
            ParameterDefinition(
                parameter_id="indicated_power",
                display_name="Indicated Power",
                display_unit="W",
                canonical_unit="WATT",
                category=ParameterCategory.ENGINE_DYNAMICS,
                status=ParameterStatus.DERIVED,
                description="Useful indicated combustion mechanical power P_ind",
                upstream_cause_ids=["heat_release_rate"],
                downstream_effect_ids=["indicated_torque"],
                telemetry_column_name="indicated_power_w",
            ),
            ParameterDefinition(
                parameter_id="indicated_torque",
                display_name="Indicated Torque",
                display_unit="N·m",
                canonical_unit="NEWTON_METER",
                category=ParameterCategory.ENGINE_DYNAMICS,
                status=ParameterStatus.DERIVED,
                description="Indicated combustion torque T_ind = P_ind / omega_eng",
                upstream_cause_ids=["indicated_power", "engine_rpm"],
                downstream_effect_ids=["engine_rpm"],
                telemetry_column_name="indicated_torque_n_m",
            ),

            # EXHAUST & THERMAL MANAGEMENT
            ParameterDefinition(
                parameter_id="exhaust_mass_flow",
                display_name="Exhaust Mass Flow",
                display_unit="kg/s",
                canonical_unit="KG_PER_SEC",
                category=ParameterCategory.ENGINE_DYNAMICS,
                status=ParameterStatus.DERIVED,
                description="Total exhaust gas mass flow rate m_dot_exh = m_dot_air + m_dot_fuel",
                upstream_cause_ids=["air_mass_flow", "fuel_mass_flow"],
                downstream_effect_ids=["exhaust_energy_available", "turbine_power"],
                telemetry_column_name="exhaust_mass_flow_kg_s",
            ),
            ParameterDefinition(
                parameter_id="exhaust_temperature",
                display_name="Exhaust Gas Temperature (Raw)",
                display_unit="°C",
                canonical_unit="KELVIN",
                category=ParameterCategory.THERMAL,
                status=ParameterStatus.DERIVED,
                description="Exhaust thermodynamic temperature T_exh",
                upstream_cause_ids=["heat_release_rate", "exhaust_mass_flow"],
                downstream_effect_ids=["egt", "turbine_power"],
                telemetry_column_name="exhaust_temp_k",
            ),
            ParameterDefinition(
                parameter_id="egt",
                display_name="Exhaust Gas Temperature",
                display_unit="°C",
                canonical_unit="KELVIN",
                category=ParameterCategory.THERMAL,
                status=ParameterStatus.DERIVED,
                description="1st-order dynamic Exhaust Gas Temperature EGT",
                upstream_cause_ids=["exhaust_temperature"],
                downstream_effect_ids=["thermal_derating"],
                telemetry_column_name="egt_degc",
            ),
            ParameterDefinition(
                parameter_id="cht",
                display_name="Cylinder Head Temperature",
                display_unit="°C",
                canonical_unit="KELVIN",
                category=ParameterCategory.THERMAL,
                status=ParameterStatus.IMPLEMENTED,
                description="1st-order dynamic Cylinder Head Temperature CHT",
                upstream_cause_ids=["heat_release_rate", "coolant_temperature", "airspeed"],
                downstream_effect_ids=["thermal_derating", "coolant_temperature"],
                telemetry_column_name="cht_degc",
            ),
            ParameterDefinition(
                parameter_id="coolant_temperature",
                display_name="Coolant Temperature",
                display_unit="°C",
                canonical_unit="KELVIN",
                category=ParameterCategory.THERMAL,
                status=ParameterStatus.DERIVED,
                description="1st-order dynamic Engine Coolant Temperature",
                upstream_cause_ids=["cht", "ambient_temperature"],
                downstream_effect_ids=[],
                telemetry_column_name="coolant_temp_degc",
            ),
            ParameterDefinition(
                parameter_id="oil_temperature",
                display_name="Oil Temperature",
                display_unit="°C",
                canonical_unit="KELVIN",
                category=ParameterCategory.LUBRICATION,
                status=ParameterStatus.IMPLEMENTED,
                description="1st-order dynamic Oil Sump Temperature T_oil",
                upstream_cause_ids=["friction_torque", "ambient_temperature"],
                downstream_effect_ids=["oil_viscosity", "thermal_derating"],
                telemetry_column_name="oil_temperature_degc",
            ),
            ParameterDefinition(
                parameter_id="injection_timing",
                display_name="Injection Timing",
                display_unit="°BTDC",
                canonical_unit="DEGREE",
                category=ParameterCategory.ENGINE_CONTROL,
                status=ParameterStatus.IMPLEMENTED,
                description="Fuel injection advance angle",
                upstream_cause_ids=["engine_rpm"],
                downstream_effect_ids=["combustion_efficiency"],
                telemetry_column_name="injection_timing_deg_btdc",
            ),
            ParameterDefinition(
                parameter_id="thermal_derating",
                display_name="Thermal Protection Derating Factor",
                display_unit="Factor",
                canonical_unit="RATIO",
                category=ParameterCategory.THERMAL,
                status=ParameterStatus.DERIVED,
                description="Thermal protection derating multiplier in [0.0, 1.0]",
                upstream_cause_ids=["cht", "egt", "oil_temperature"],
                downstream_effect_ids=["fuel_mass_flow"],
                telemetry_column_name="thermal_derating_factor",
            ),
            ParameterDefinition(
                parameter_id="engine_thermal_state",
                display_name="Engine Thermal State",
                display_unit="State",
                canonical_unit="TEXT",
                category=ParameterCategory.THERMAL,
                status=ParameterStatus.DERIVED,
                description="Composite dynamic thermal state indicator",
                upstream_cause_ids=["cht", "egt", "coolant_temperature"],
                downstream_effect_ids=[],
                telemetry_column_name="thermal_state_str",
            ),

            # CONTROL & ENGINE DYNAMICS
            ParameterDefinition(
                parameter_id="throttle",
                display_name="Throttle Demand",
                display_unit="%",
                canonical_unit="PERCENT",
                category=ParameterCategory.ENGINE_CONTROL,
                status=ParameterStatus.IMPLEMENTED,
                description="Pilot or flight controller throttle command theta",
                upstream_cause_ids=[],
                downstream_effect_ids=["fuel_mass_flow"],
                telemetry_column_name="throttle_percent",
            ),
            ParameterDefinition(
                parameter_id="manifold_pressure",
                display_name="Manifold Pressure",
                display_unit="bar",
                canonical_unit="PASCAL",
                category=ParameterCategory.ENGINE_DYNAMICS,
                status=ParameterStatus.DERIVED,
                description="Intake manifold absolute pressure MAP",
                upstream_cause_ids=["compressor_pressure_ratio", "ambient_pressure"],
                downstream_effect_ids=["air_mass_flow"],
                telemetry_column_name="manifold_pressure_pa",
            ),
            ParameterDefinition(
                parameter_id="engine_rpm",
                display_name="Engine Speed",
                display_unit="RPM",
                canonical_unit="RAD_PER_SEC",
                category=ParameterCategory.ENGINE_DYNAMICS,
                status=ParameterStatus.IMPLEMENTED,
                description="Engine crankshaft rotational speed omega",
                upstream_cause_ids=["indicated_torque", "starter_torque", "engine_load_torque", "alternator_torque", "friction_torque"],
                downstream_effect_ids=["air_mass_flow", "propeller_rpm", "alternator_power", "vibration_rms"],
                telemetry_column_name="engine_rpm",
            ),
            ParameterDefinition(
                parameter_id="air_mass_flow",
                display_name="Air Mass Flow",
                display_unit="kg/h",
                canonical_unit="KG_PER_SEC",
                category=ParameterCategory.ENGINE_DYNAMICS,
                status=ParameterStatus.DERIVED,
                description="Intake air mass flow rate m_air",
                upstream_cause_ids=["manifold_pressure", "air_density", "engine_rpm"],
                downstream_effect_ids=["fuel_mass_flow", "air_fuel_ratio", "compressor_power"],
                telemetry_column_name="air_mass_flow_kg_s",
            ),
            ParameterDefinition(
                parameter_id="fuel_flow",
                display_name="Fuel Mass Flow",
                display_unit="kg/h",
                canonical_unit="KG_PER_SEC",
                category=ParameterCategory.ENGINE_DYNAMICS,
                status=ParameterStatus.IMPLEMENTED,
                description="Total fuel delivery rate m_fuel",
                upstream_cause_ids=["fuel_mass_flow"],
                downstream_effect_ids=[],
                telemetry_column_name="fuel_flow_kg_h",
            ),
            ParameterDefinition(
                parameter_id="propeller_load_torque",
                display_name="Propeller Load Torque",
                display_unit="N·m",
                canonical_unit="NEWTON_METER",
                category=ParameterCategory.ENGINE_DYNAMICS,
                status=ParameterStatus.DERIVED,
                description="Propeller mechanical shaft load T_load",
                upstream_cause_ids=["propeller_rpm", "air_density"],
                downstream_effect_ids=["engine_load_torque"],
                telemetry_column_name="propeller_load_torque_n_m",
            ),
            ParameterDefinition(
                parameter_id="friction_torque",
                display_name="Friction Torque",
                display_unit="N·m",
                canonical_unit="NEWTON_METER",
                category=ParameterCategory.ENGINE_DYNAMICS,
                status=ParameterStatus.DERIVED,
                description="Engine mechanical friction torque T_fric",
                upstream_cause_ids=["engine_rpm", "oil_viscosity", "bearing_degradation"],
                downstream_effect_ids=["engine_rpm", "oil_heat_generation"],
                telemetry_column_name="friction_torque_n_m",
            ),

            # LUBRICATION & DEGRADATION
            ParameterDefinition(
                parameter_id="oil_viscosity",
                display_name="Oil Viscosity",
                display_unit="Pa·s",
                canonical_unit="PASCAL_SECOND",
                category=ParameterCategory.LUBRICATION,
                status=ParameterStatus.DERIVED,
                description="Vogel dynamic oil viscosity mu(T_oil)",
                upstream_cause_ids=["oil_temperature"],
                downstream_effect_ids=["temperature_dependent_friction", "friction_torque", "bearing_degradation"],
                telemetry_column_name="oil_viscosity_pa_s",
            ),
            ParameterDefinition(
                parameter_id="oil_pressure",
                display_name="Oil Pressure",
                display_unit="bar",
                canonical_unit="PASCAL",
                category=ParameterCategory.LUBRICATION,
                status=ParameterStatus.CONFIGURED,
                description="Engine oil pressure P_oil",
                upstream_cause_ids=["engine_rpm", "oil_viscosity"],
                downstream_effect_ids=["bearing_degradation"],
                telemetry_column_name="oil_pressure_bar",
            ),
            ParameterDefinition(
                parameter_id="oil_heat_generation",
                display_name="Oil Heat Generation",
                display_unit="W",
                canonical_unit="WATT",
                category=ParameterCategory.LUBRICATION,
                status=ParameterStatus.DERIVED,
                description="Oil thermal heat generation rate Q_oil_gen",
                upstream_cause_ids=["friction_torque", "cht"],
                downstream_effect_ids=["oil_temperature"],
                telemetry_column_name="oil_heat_generation_w",
            ),
            ParameterDefinition(
                parameter_id="oil_heat_rejection",
                display_name="Oil Cooler Rejection",
                display_unit="W",
                canonical_unit="WATT",
                category=ParameterCategory.LUBRICATION,
                status=ParameterStatus.DERIVED,
                description="Oil cooler heat rejection rate Q_oil_cool",
                upstream_cause_ids=["oil_temperature", "ambient_temperature"],
                downstream_effect_ids=["oil_temperature"],
                telemetry_column_name="oil_heat_rejection_w",
            ),
            ParameterDefinition(
                parameter_id="temperature_dependent_friction",
                display_name="Viscous Friction Contribution",
                display_unit="N·m",
                canonical_unit="NEWTON_METER",
                category=ParameterCategory.LUBRICATION,
                status=ParameterStatus.DERIVED,
                description="Viscosity-modified viscous friction component T_fric,visc",
                upstream_cause_ids=["oil_viscosity", "engine_rpm"],
                downstream_effect_ids=["friction_torque"],
                telemetry_column_name="viscosity_friction_n_m",
            ),
            ParameterDefinition(
                parameter_id="bearing_degradation",
                display_name="Bearing Degradation",
                display_unit="State",
                canonical_unit="RATIO",
                category=ParameterCategory.DEGRADATION,
                status=ParameterStatus.IMPLEMENTED,
                description="Cumulative bearing wear degradation state D_bearing",
                upstream_cause_ids=["engine_rpm", "indicated_torque", "oil_viscosity"],
                downstream_effect_ids=["friction_torque", "vibration_acceleration"],
                telemetry_column_name="degradation_bearing",
            ),
            ParameterDefinition(
                parameter_id="ring_degradation",
                display_name="Ring Degradation",
                display_unit="State",
                canonical_unit="RATIO",
                category=ParameterCategory.DEGRADATION,
                status=ParameterStatus.IMPLEMENTED,
                description="Cumulative piston ring wear degradation state D_ring",
                upstream_cause_ids=["engine_rpm", "cht"],
                downstream_effect_ids=["combustion_efficiency"],
                telemetry_column_name="degradation_ring",
            ),
            ParameterDefinition(
                parameter_id="injector_degradation",
                display_name="Injector Degradation",
                display_unit="State",
                canonical_unit="RATIO",
                category=ParameterCategory.DEGRADATION,
                status=ParameterStatus.IMPLEMENTED,
                description="Cumulative injector erosion wear degradation state D_injector",
                upstream_cause_ids=["fuel_mass_flow", "cht"],
                downstream_effect_ids=["combustion_efficiency"],
                telemetry_column_name="degradation_injector",
            ),
            ParameterDefinition(
                parameter_id="bearing_wear",
                display_name="Bearing Wear State",
                display_unit="State",
                canonical_unit="RATIO",
                category=ParameterCategory.DEGRADATION,
                status=ParameterStatus.IMPLEMENTED,
                description="Bearing wear degradation state D_bearing",
                upstream_cause_ids=["bearing_degradation"],
                downstream_effect_ids=[],
                telemetry_column_name="degradation_bearing",
            ),
            ParameterDefinition(
                parameter_id="injector_wear",
                display_name="Injector Wear State",
                display_unit="State",
                canonical_unit="RATIO",
                category=ParameterCategory.DEGRADATION,
                status=ParameterStatus.IMPLEMENTED,
                description="Fuel injector wear state D_injector",
                upstream_cause_ids=["injector_degradation"],
                downstream_effect_ids=[],
                telemetry_column_name="degradation_injector",
            ),
            ParameterDefinition(
                parameter_id="ring_wear",
                display_name="Piston Ring Wear State",
                display_unit="State",
                canonical_unit="RATIO",
                category=ParameterCategory.DEGRADATION,
                status=ParameterStatus.IMPLEMENTED,
                description="Piston ring wear state D_ring",
                upstream_cause_ids=["ring_degradation"],
                downstream_effect_ids=[],
                telemetry_column_name="degradation_ring",
            ),
            ParameterDefinition(
                parameter_id="vibration_acceleration",
                display_name="Vibration Acceleration",
                display_unit="m/s²",
                canonical_unit="M_PER_SEC2",
                category=ParameterCategory.MECHANICAL,
                status=ParameterStatus.DERIVED,
                description="1000 Hz instantaneous structural vibration acceleration a(t)",
                upstream_cause_ids=["engine_rpm", "indicated_torque", "propeller_torque", "bearing_degradation"],
                downstream_effect_ids=["vibration_rms"],
                telemetry_column_name="vibration_acceleration_m_s2",
            ),
            ParameterDefinition(
                parameter_id="vibration_rms",
                display_name="Vibration RMS",
                display_unit="m/s²",
                canonical_unit="M_PER_SEC2",
                category=ParameterCategory.MECHANICAL,
                status=ParameterStatus.DERIVED,
                description="1000 Hz structural acceleration vibration RMS",
                upstream_cause_ids=["vibration_acceleration"],
                downstream_effect_ids=[],
                telemetry_column_name="vibration_rms_m_s2",
            ),
            ParameterDefinition(
                parameter_id="vibration_dominant_frequency",
                display_name="Vibration Dominant Frequency",
                display_unit="Hz",
                canonical_unit="HERTZ",
                category=ParameterCategory.MECHANICAL,
                status=ParameterStatus.DERIVED,
                description="Dominant spectral vibration frequency peak",
                upstream_cause_ids=["engine_rpm"],
                downstream_effect_ids=[],
                telemetry_column_name="vibration_dominant_freq_hz",
            ),

            # ELECTRICAL & BATTERY
            ParameterDefinition(
                parameter_id="bus_voltage",
                display_name="Bus Voltage",
                display_unit="V",
                canonical_unit="VOLT",
                category=ParameterCategory.ELECTRICAL,
                status=ParameterStatus.IMPLEMENTED,
                description="Electrical bus terminal voltage V_bus",
                upstream_cause_ids=["battery_soc", "alternator_power"],
                downstream_effect_ids=["alternator_torque", "bus_current"],
                telemetry_column_name="bus_voltage_v",
            ),
            ParameterDefinition(
                parameter_id="bus_current",
                display_name="Bus Current",
                display_unit="A",
                canonical_unit="AMPERE",
                category=ParameterCategory.ELECTRICAL,
                status=ParameterStatus.DERIVED,
                description="Total electrical bus current I_bus",
                upstream_cause_ids=["electrical_load_power", "bus_voltage"],
                downstream_effect_ids=[],
                telemetry_column_name="bus_current_a",
            ),
            ParameterDefinition(
                parameter_id="alternator_rpm",
                display_name="Alternator Speed",
                display_unit="RPM",
                canonical_unit="RAD_PER_SEC",
                category=ParameterCategory.ELECTRICAL,
                status=ParameterStatus.DERIVED,
                description="Alternator rotational speed N_alt",
                upstream_cause_ids=["engine_rpm"],
                downstream_effect_ids=["alternator_power"],
                telemetry_column_name="alternator_rpm",
            ),
            ParameterDefinition(
                parameter_id="alternator_power",
                display_name="Alternator Power Output",
                display_unit="W",
                canonical_unit="WATT",
                category=ParameterCategory.ELECTRICAL,
                status=ParameterStatus.DERIVED,
                description="Alternator electrical power generation P_alt",
                upstream_cause_ids=["engine_rpm", "bus_voltage", "electrical_load_power"],
                downstream_effect_ids=["alternator_torque", "bus_voltage", "battery_current"],
                telemetry_column_name="alternator_power_w",
            ),
            ParameterDefinition(
                parameter_id="alternator_torque",
                display_name="Alternator Shaft Load Torque",
                display_unit="N·m",
                canonical_unit="NEWTON_METER",
                category=ParameterCategory.ELECTRICAL,
                status=ParameterStatus.DERIVED,
                description="Mechanical shaft load torque exerted by alternator T_alt",
                upstream_cause_ids=["alternator_power", "engine_rpm"],
                downstream_effect_ids=["engine_rpm"],
                telemetry_column_name="alternator_torque_n_m",
            ),
            ParameterDefinition(
                parameter_id="alternator_current",
                display_name="Alternator Current",
                display_unit="A",
                canonical_unit="AMPERE",
                category=ParameterCategory.ELECTRICAL,
                status=ParameterStatus.DERIVED,
                description="Alternator output generation current I_alt",
                upstream_cause_ids=["alternator_power", "bus_voltage"],
                downstream_effect_ids=[],
                telemetry_column_name="alternator_current_a",
            ),
            ParameterDefinition(
                parameter_id="alternator_load_torque",
                display_name="Alternator Shaft Load",
                display_unit="N·m",
                canonical_unit="NEWTON_METER",
                category=ParameterCategory.ELECTRICAL,
                status=ParameterStatus.DERIVED,
                description="Mechanical shaft torque load exerted by alternator T_alt",
                upstream_cause_ids=["alternator_torque"],
                downstream_effect_ids=[],
                telemetry_column_name="alternator_load_torque_n_m",
            ),
            ParameterDefinition(
                parameter_id="battery_soc",
                display_name="Battery State-of-Charge",
                display_unit="%",
                canonical_unit="PERCENT",
                category=ParameterCategory.ELECTRICAL,
                status=ParameterStatus.IMPLEMENTED,
                description="Battery State of Charge (SOC)",
                upstream_cause_ids=["battery_current"],
                downstream_effect_ids=["battery_voltage", "bus_voltage"],
                telemetry_column_name="battery_soc_percent",
            ),
            ParameterDefinition(
                parameter_id="battery_voltage",
                display_name="Battery Voltage",
                display_unit="V",
                canonical_unit="VOLT",
                category=ParameterCategory.ELECTRICAL,
                status=ParameterStatus.IMPLEMENTED,
                description="Battery terminal voltage V_bat",
                upstream_cause_ids=["battery_soc"],
                downstream_effect_ids=["bus_voltage"],
                telemetry_column_name="battery_voltage_v",
            ),
            ParameterDefinition(
                parameter_id="battery_current",
                display_name="Battery Current",
                display_unit="A",
                canonical_unit="AMPERE",
                category=ParameterCategory.ELECTRICAL,
                status=ParameterStatus.DERIVED,
                description="Battery current I_batt (+ = discharge, - = charge)",
                upstream_cause_ids=["electrical_load_power", "alternator_power"],
                downstream_effect_ids=["battery_soc"],
                telemetry_column_name="battery_current_a",
            ),
            ParameterDefinition(
                parameter_id="battery_power",
                display_name="Battery Power",
                display_unit="W",
                canonical_unit="WATT",
                category=ParameterCategory.ELECTRICAL,
                status=ParameterStatus.DERIVED,
                description="Battery chemical power rate P_batt",
                upstream_cause_ids=["battery_current", "battery_voltage"],
                downstream_effect_ids=["battery_soc"],
                telemetry_column_name="battery_power_w",
            ),
            ParameterDefinition(
                parameter_id="starter_torque",
                display_name="Starter Cranking Torque",
                display_unit="N·m",
                canonical_unit="NEWTON_METER",
                category=ParameterCategory.ELECTRICAL,
                status=ParameterStatus.DERIVED,
                description="Starter motor mechanical cranking torque T_starter",
                upstream_cause_ids=["starter_power", "engine_rpm", "battery_soc"],
                downstream_effect_ids=["engine_rpm"],
                telemetry_column_name="starter_torque_n_m",
            ),
            ParameterDefinition(
                parameter_id="starter_power",
                display_name="Starter Motor Power",
                display_unit="W",
                canonical_unit="WATT",
                category=ParameterCategory.ELECTRICAL,
                status=ParameterStatus.DERIVED,
                description="Starter motor electrical power draw P_starter",
                upstream_cause_ids=["battery_voltage"],
                downstream_effect_ids=["starter_torque", "battery_current"],
                telemetry_column_name="starter_power_w",
            ),
            ParameterDefinition(
                parameter_id="electrical_load_power",
                display_name="Electrical Load Demand",
                display_unit="W",
                canonical_unit="WATT",
                category=ParameterCategory.ELECTRICAL,
                status=ParameterStatus.IMPLEMENTED,
                description="Total electrical power load demand P_load",
                upstream_cause_ids=[],
                downstream_effect_ids=["bus_current", "alternator_power", "battery_current"],
                telemetry_column_name="electrical_load_w",
            ),

            # THERMAL ADDITIONAL
            ParameterDefinition(
                parameter_id="cooling_heat_rejection",
                display_name="Cooling Heat Rejection",
                display_unit="W",
                canonical_unit="WATT",
                category=ParameterCategory.THERMAL,
                status=ParameterStatus.DERIVED,
                description="Convective cooling thermal rejection rate Q_cooling",
                upstream_cause_ids=["cht", "airspeed", "ambient_temperature"],
                downstream_effect_ids=["cht"],
                telemetry_column_name="cooling_heat_rejection_w",
            ),
            ParameterDefinition(
                parameter_id="wall_heat_generation",
                display_name="Wall Heat Transfer",
                display_unit="W",
                canonical_unit="WATT",
                category=ParameterCategory.THERMAL,
                status=ParameterStatus.DERIVED,
                description="Cylinder wall heat transfer generation rate Q_wall",
                upstream_cause_ids=["fuel_mass_flow", "combustion_efficiency"],
                downstream_effect_ids=["cht"],
                telemetry_column_name="wall_heat_generation_w",
            ),
            ParameterDefinition(
                parameter_id="cht_cyl1",
                display_name="CHT Cylinder 1",
                display_unit="°C",
                canonical_unit="KELVIN",
                category=ParameterCategory.THERMAL,
                status=ParameterStatus.CONFIGURED,
                description="Cylinder Head Temperature 1",
                upstream_cause_ids=["cht"],
                downstream_effect_ids=[],
                telemetry_column_name="cht_cyl1_degc",
            ),
            ParameterDefinition(
                parameter_id="cht_cyl2",
                display_name="CHT Cylinder 2",
                display_unit="°C",
                canonical_unit="KELVIN",
                category=ParameterCategory.THERMAL,
                status=ParameterStatus.CONFIGURED,
                description="Cylinder Head Temperature 2",
                upstream_cause_ids=["cht"],
                downstream_effect_ids=[],
                telemetry_column_name="cht_cyl2_degc",
            ),
            ParameterDefinition(
                parameter_id="cht_cyl3",
                display_name="CHT Cylinder 3",
                display_unit="°C",
                canonical_unit="KELVIN",
                category=ParameterCategory.THERMAL,
                status=ParameterStatus.CONFIGURED,
                description="Cylinder Head Temperature 3",
                upstream_cause_ids=["cht"],
                downstream_effect_ids=[],
                telemetry_column_name="cht_cyl3_degc",
            ),
            ParameterDefinition(
                parameter_id="cht_cyl4",
                display_name="CHT Cylinder 4",
                display_unit="°C",
                canonical_unit="KELVIN",
                category=ParameterCategory.THERMAL,
                status=ParameterStatus.CONFIGURED,
                description="Cylinder Head Temperature 4",
                upstream_cause_ids=["cht"],
                downstream_effect_ids=[],
                telemetry_column_name="cht_cyl4_degc",
            ),
            ParameterDefinition(
                parameter_id="egt_cyl1",
                display_name="EGT Cylinder 1",
                display_unit="°C",
                canonical_unit="KELVIN",
                category=ParameterCategory.THERMAL,
                status=ParameterStatus.CONFIGURED,
                description="Exhaust Gas Temperature 1",
                upstream_cause_ids=["egt"],
                downstream_effect_ids=[],
                telemetry_column_name="egt_cyl1_degc",
            ),
            ParameterDefinition(
                parameter_id="egt_cyl2",
                display_name="EGT Cylinder 2",
                display_unit="°C",
                canonical_unit="KELVIN",
                category=ParameterCategory.THERMAL,
                status=ParameterStatus.CONFIGURED,
                description="Exhaust Gas Temperature 2",
                upstream_cause_ids=["egt"],
                downstream_effect_ids=[],
                telemetry_column_name="egt_cyl2_degc",
            ),
            ParameterDefinition(
                parameter_id="egt_cyl3",
                display_name="EGT Cylinder 3",
                display_unit="°C",
                canonical_unit="KELVIN",
                category=ParameterCategory.THERMAL,
                status=ParameterStatus.CONFIGURED,
                description="Exhaust Gas Temperature 3",
                upstream_cause_ids=["egt"],
                downstream_effect_ids=[],
                telemetry_column_name="egt_cyl3_degc",
            ),
            ParameterDefinition(
                parameter_id="egt_cyl4",
                display_name="EGT Cylinder 4",
                display_unit="°C",
                canonical_unit="KELVIN",
                category=ParameterCategory.THERMAL,
                status=ParameterStatus.CONFIGURED,
                description="Exhaust Gas Temperature 4",
                upstream_cause_ids=["egt"],
                downstream_effect_ids=[],
                telemetry_column_name="egt_cyl4_degc",
            ),
            ParameterDefinition(
                parameter_id="cooling_airflow",
                display_name="Cooling Airflow",
                display_unit="m/s",
                canonical_unit="M_PER_SEC",
                category=ParameterCategory.THERMAL,
                status=ParameterStatus.PLANNED,
                description="Ram air cooling airflow velocity",
                upstream_cause_ids=["airspeed"],
                downstream_effect_ids=["cooling_heat_rejection"],
                telemetry_column_name="cooling_airflow_m_s",
            ),

            # EFFICIENCY
            ParameterDefinition(
                parameter_id="brake_thermal_efficiency",
                display_name="Brake Thermal Efficiency",
                display_unit="%",
                canonical_unit="PERCENT",
                category=ParameterCategory.ENGINE_DYNAMICS,
                status=ParameterStatus.DERIVED,
                description="Overall Brake Thermal Efficiency (BTE)",
                upstream_cause_ids=["indicated_torque", "fuel_mass_flow", "engine_rpm"],
                downstream_effect_ids=[],
                telemetry_column_name="brake_thermal_efficiency_percent",
            ),
        ]

        for p in params:
            self.register(p)
