"""
Module 02 Intake Manifold & Airflow Physics Subsystem (Phase 3.4 Physically Closed Architecture).
SIH26054 — Module 02 Engine Simulator.
"""

import math
import warnings
from typing import Tuple


class IntakeTurbochargerError(ValueError):
    """Raised when numerical safety or physical boundary violations occur in intake/turbocharger physics."""
    pass


class IntakeTurbochargerModel:
    """
    Intake Manifold, Turbocharger Compressor, and Engine Air Mass Flow Physics Subsystem.
    All calculations strictly use Canonical SI Units (Pascals, Kelvin, kg/m^3, m^3, kg/s, rad/s).
    """

    GAS_CONSTANT_DRY_AIR: float = 287.058      # Rd (J/(kg K)) - Physical Constant
    GAMMA_AIR: float = 1.4                     # Ratio of Specific Heats (Cp/Cv) - Physical Constant
    GAMMA_EXPONENT: float = (1.4 - 1.0) / 1.4  # (gamma - 1) / gamma = 0.285714... - Physical Constant

    @classmethod
    def validate_inputs(
        cls,
        ambient_pressure_pa: float,
        ambient_temp_k: float,
        engine_rpm: float,
        displacement_m3: float
    ) -> None:
        """Validates numerical safety and physical bounds for intake physics inputs."""
        if math.isnan(ambient_pressure_pa) or math.isinf(ambient_pressure_pa) or ambient_pressure_pa <= 0:
            raise IntakeTurbochargerError(f"Invalid ambient pressure: {ambient_pressure_pa} Pa.")

        if math.isnan(ambient_temp_k) or math.isinf(ambient_temp_k) or ambient_temp_k <= 0:
            raise IntakeTurbochargerError(f"Invalid ambient temperature: {ambient_temp_k} K.")

        if math.isnan(engine_rpm) or math.isinf(engine_rpm) or engine_rpm < 0:
            raise IntakeTurbochargerError(f"Invalid engine RPM: {engine_rpm}.")

        if math.isnan(displacement_m3) or math.isinf(displacement_m3) or displacement_m3 <= 0:
            raise IntakeTurbochargerError(f"Invalid engine displacement: {displacement_m3} m^3.")

    @classmethod
    def compute_manifold_absolute_pressure(
        cls,
        ambient_pressure_pa: float,
        throttle_percent: float,
        max_map_pa: float,
        max_pressure_ratio: float
    ) -> Tuple[float, float]:
        """
        DEPRECATED PHASE 3.2 PARAMETRIC PLACEHOLDER:
        This placeholder function is deprecated in Phase 3.4.
        Manifold Absolute Pressure (MAP) is now dynamically generated by TurboRunner via closed-loop turbine dynamics.
        """
        warnings.warn(
            "compute_manifold_absolute_pressure is deprecated in Phase 3.4. Use TurboRunner for closed-loop MAP generation.",
            DeprecationWarning,
            stacklevel=2
        )
        p_amb = float(ambient_pressure_pa)
        th = max(0.0, min(100.0, float(throttle_percent)))
        p_max = float(max_map_pa)
        pi_max = float(max_pressure_ratio)

        if math.isnan(p_amb) or math.isinf(p_amb) or p_amb <= 0:
            raise IntakeTurbochargerError(f"Invalid ambient pressure: {ambient_pressure_pa} Pa.")

        if math.isnan(p_max) or math.isinf(p_max) or p_max <= 0 or math.isnan(pi_max) or math.isinf(pi_max) or pi_max < 1.0:
            raise IntakeTurbochargerError("Invalid turbocharger pressure limits in configuration.")

        max_boost_delta = min(max(0.0, p_max - p_amb), p_amb * (pi_max - 1.0))
        p_map = p_amb + ((th / 100.0) * max_boost_delta)
        pi_c = p_map / p_amb if p_amb > 0 else 1.0

        return (p_map, pi_c)

    @classmethod
    def compute_gauge_boost_pressure(
        cls,
        manifold_absolute_pressure_pa: float,
        ambient_pressure_pa: float
    ) -> float:
        """
        PHYSICAL MODEL:
        Calculates Gauge Boost Pressure:
        P_boost_gauge = max(0.0, P_manifold_absolute - P_ambient)
        """
        p_map = float(manifold_absolute_pressure_pa)
        p_amb = float(ambient_pressure_pa)

        if math.isnan(p_map) or math.isinf(p_map) or math.isnan(p_amb) or math.isinf(p_amb):
            raise IntakeTurbochargerError("Pressures cannot be NaN or Inf.")

        return max(0.0, p_map - p_amb)

    @classmethod
    def compute_turbo_shaft_speed(
        cls,
        engine_rpm: float,
        throttle_percent: float,
        rated_engine_rpm: float,
        max_turbo_rpm: float
    ) -> float:
        """
        DEPRECATED PHASE 3.2 PARAMETRIC PLACEHOLDER:
        This placeholder function is deprecated in Phase 3.4.
        Turbo shaft speed is now integrated dynamically via J_turbo * d(omega)/dt = tau_turbine - tau_compressor - tau_friction.
        """
        warnings.warn(
            "compute_turbo_shaft_speed is deprecated in Phase 3.4. Use TurboRunner for shaft dynamics.",
            DeprecationWarning,
            stacklevel=2
        )
        th = max(0.0, min(100.0, float(throttle_percent)))
        n_eng = max(0.0, float(engine_rpm))
        n_rated = float(rated_engine_rpm)
        n_tmax = float(max_turbo_rpm)

        if math.isnan(n_rated) or math.isinf(n_rated) or n_rated <= 0:
            raise IntakeTurbochargerError(f"Invalid rated engine RPM: {rated_engine_rpm}.")

        if math.isnan(n_tmax) or math.isinf(n_tmax) or n_tmax <= 0:
            raise IntakeTurbochargerError(f"Invalid max turbo RPM: {max_turbo_rpm}.")

        rpm_ratio = min(1.2, n_eng / n_rated)
        n_turbo = (th / 100.0) * rpm_ratio * n_tmax
        return max(0.0, min(n_tmax * 1.1, n_turbo))

    @classmethod
    def compute_compressor_outlet_temperature(
        cls,
        ambient_temp_k: float,
        compressor_pressure_ratio: float,
        compressor_efficiency: float
    ) -> float:
        """
        PHYSICAL MODEL:
        Computes compressor outlet discharge temperature T_comp_out in Kelvin via isentropic relation:
        T_comp_out = T_amb * [ 1 + (1 / eta_c) * ( (pi_c)^((gamma-1)/gamma) - 1 ) ]
        """
        t_amb = float(ambient_temp_k)
        pi_c = max(1.0, float(compressor_pressure_ratio))
        eta_c = float(compressor_efficiency)

        if math.isnan(t_amb) or math.isinf(t_amb) or t_amb <= 0:
            raise IntakeTurbochargerError(f"Invalid ambient temperature: {ambient_temp_k} K.")

        if math.isnan(eta_c) or math.isinf(eta_c) or not (0.1 <= eta_c <= 1.0):
            raise IntakeTurbochargerError(f"Compressor efficiency eta_c must be in (0.1, 1.0]. Got {compressor_efficiency}.")

        t_isentropic_ratio = math.pow(pi_c, cls.GAMMA_EXPONENT)
        t_comp_out = t_amb * (1.0 + (1.0 / eta_c) * (t_isentropic_ratio - 1.0))
        return t_comp_out

    @classmethod
    def compute_intake_air_density(
        cls,
        manifold_absolute_pressure_pa: float,
        intake_temp_k: float
    ) -> float:
        """
        PHYSICAL MODEL:
        Computes intake manifold air mass density rho_intake in kg/m^3 via Ideal Gas Law:
        rho_intake = P_manifold_absolute / (R_d * T_intake)
        """
        p_map = float(manifold_absolute_pressure_pa)
        t_in = float(intake_temp_k)

        if math.isnan(p_map) or math.isinf(p_map) or p_map <= 0:
            raise IntakeTurbochargerError(f"Invalid manifold absolute pressure: {manifold_absolute_pressure_pa} Pa.")

        if math.isnan(t_in) or math.isinf(t_in) or t_in <= 0:
            raise IntakeTurbochargerError(f"Invalid intake temperature: {intake_temp_k} K.")

        return p_map / (cls.GAS_CONSTANT_DRY_AIR * t_in)

    @classmethod
    def compute_volumetric_efficiency(
        cls,
        engine_rpm: float,
        manifold_absolute_pressure_pa: float,
        rated_rpm: float
    ) -> float:
        """
        PHYSICAL MODEL:
        Computes speed and manifold pressure dependent engine volumetric efficiency eta_v.
        """
        n_eng = max(0.0, float(engine_rpm))
        n_rated = float(rated_rpm)

        if math.isnan(n_rated) or math.isinf(n_rated) or n_rated <= 0:
            raise IntakeTurbochargerError(f"Invalid rated RPM: {rated_rpm}.")

        rpm_ratio = n_eng / n_rated
        eta_base = 0.82 + 0.10 * rpm_ratio - 0.08 * (rpm_ratio * rpm_ratio)
        return max(0.65, min(0.95, eta_base))

    @classmethod
    def compute_engine_air_mass_flow(
        cls,
        engine_rpm: float,
        intake_air_density_kg_m3: float,
        displacement_m3: float,
        volumetric_efficiency: float
    ) -> Tuple[float, float]:
        """
        PHYSICAL MODEL:
        Computes engine intake air mass flow rate for a 4-stroke reciprocating engine:
        m_dot_air_kg_s = eta_v * rho_intake * V_d * (RPM / (60 * 2))
        Returns Tuple of (m_dot_air_kg_s, m_dot_air_kg_h).
        """
        rpm = max(0.0, float(engine_rpm))
        rho_in = float(intake_air_density_kg_m3)
        v_d = float(displacement_m3)
        eta_v = float(volumetric_efficiency)

        if math.isnan(rho_in) or math.isinf(rho_in) or rho_in <= 0:
            raise IntakeTurbochargerError(f"Invalid intake density: {intake_air_density_kg_m3} kg/m^3.")

        if math.isnan(v_d) or math.isinf(v_d) or v_d <= 0:
            raise IntakeTurbochargerError(f"Invalid displacement: {displacement_m3} m^3.")

        if math.isnan(eta_v) or math.isinf(eta_v) or eta_v <= 0:
            raise IntakeTurbochargerError(f"Invalid volumetric efficiency: {volumetric_efficiency}.")

        cycles_per_sec = rpm / 120.0
        m_dot_kg_s = eta_v * rho_in * v_d * cycles_per_sec
        m_dot_kg_h = m_dot_kg_s * 3600.0

        return (m_dot_kg_s, m_dot_kg_h)
