"""
Expected State Model — Physical Target Values Derived from Rotax 914 Simulation.
SIH26054 — Module 03 Digital Twin Core.
"""

from dataclasses import dataclass
from typing import Any, Dict, Optional


@dataclass
class ExpectedState:
    """
    Represents physical target/expected outputs generated by the physics model
    under identical operating context and environmental conditions.
    Contains complete 18 internal Category C parameters.
    """
    timestamp: float = 0.0
    sequence_number: int = 0
    engine_id: str = "engine_1"
    aircraft_id: str = "rotax_914_uav"

    # Physics Expected Engine Parameters (18 Category C Internal Parameters)
    rpm: float = 0.0
    map_bar: float = 1.01325
    turbo_rpm: float = 0.0
    airflow_kg_h: float = 0.0
    fuel_flow_kg_h: float = 0.0
    afr: float = 14.7
    combustion_energy: Optional[float] = None
    combustion_efficiency: float = 0.0
    indicated_power_kw: float = 0.0
    torque_n_m: float = 0.0
    egt_c: float = 15.0
    cht_c: float = 15.0
    coolant_temp_c: float = 15.0
    oil_temp_c: float = 15.0
    oil_pressure_bar: float = 0.0
    turbo_boost_bar: float = 0.0
    gearbox_rpm: float = 0.0
    propeller_load_nm: float = 0.0
    thrust_n: float = 0.0

    # Physics Expected Environment & Flight Dynamics
    airspeed_m_s: float = 0.0
    altitude_m: float = 0.0
    ambient_temp_c: float = 15.0
    ambient_pressure_kpa: float = 101.325
    ambient_density_kg_m3: float = 1.225
    wind_m_s: float = 0.0

    model_confidence: float = 1.0

    def to_dict(self) -> Dict[str, Any]:
        """Serializes ExpectedState to a dictionary."""
        return {
            "timestamp": self.timestamp,
            "sequence_number": self.sequence_number,
            "engine_id": self.engine_id,
            "aircraft_id": self.aircraft_id,
            "rpm": round(self.rpm, 2),
            "map_bar": round(self.map_bar, 4),
            "turbo_rpm": round(self.turbo_rpm, 1),
            "airflow_kg_h": round(self.airflow_kg_h, 3),
            "fuel_flow_kg_h": round(self.fuel_flow_kg_h, 3),
            "afr": round(self.afr, 2),
            "combustion_energy": round(self.combustion_energy, 2) if self.combustion_energy is not None else None,
            "combustion_efficiency": round(self.combustion_efficiency, 4),
            "indicated_power_kw": round(self.indicated_power_kw, 2),
            "torque_n_m": round(self.torque_n_m, 2),
            "egt_c": round(self.egt_c, 2),
            "cht_c": round(self.cht_c, 2),
            "coolant_temp_c": round(self.coolant_temp_c, 2),
            "oil_temp_c": round(self.oil_temp_c, 2),
            "oil_pressure_bar": round(self.oil_pressure_bar, 4),
            "turbo_boost_bar": round(self.turbo_boost_bar, 4),
            "gearbox_rpm": round(self.gearbox_rpm, 2),
            "propeller_load_nm": round(self.propeller_load_nm, 2),
            "thrust_n": round(self.thrust_n, 2),
            "airspeed_m_s": round(self.airspeed_m_s, 2),
            "altitude_m": round(self.altitude_m, 1),
            "ambient_temp_c": round(self.ambient_temp_c, 2),
            "ambient_pressure_kpa": round(self.ambient_pressure_kpa, 2),
            "ambient_density_kg_m3": round(self.ambient_density_kg_m3, 4),
            "wind_m_s": round(self.wind_m_s, 2),
            "model_confidence": self.model_confidence,
        }
