"""
Module 02 Intake Manifold & Airflow Simulation Integration Runner (Phase 3.4 Hardened Architecture).
SIH26054 — Module 02 Engine Simulator.
"""

from typing import Any, Dict, Optional
from src.module02.config.config_loader import ConfigLoader
from src.module02.core.clock import SimulationClock
from src.module02.models.states import EngineState, SimulationState
from src.module02.physics.intake_turbocharger import IntakeTurbochargerModel


class IntakeRunner:
    """
    Integration Runner for Intake Manifold, Turbocharger Compressor, and Air Mass Flow physics.
    Supports Phase 3.4 physically closed-loop MAP generated by TurboRunner.
    """

    def __init__(self, clock: Optional[SimulationClock] = None, engine_config: Optional[Dict[str, Any]] = None) -> None:
        self.clock = clock if clock is not None else SimulationClock()
        self.state = SimulationState()
        self.engine_config = engine_config if engine_config is not None else ConfigLoader.load_engine_config()
        self._initialize_twin_engines()

    def _initialize_twin_engines(self) -> None:
        """Initializes independent EngineState instances for Engine 1 and Engine 2."""
        self.state.engines[1] = EngineState(engine_index=1, engine_id="engine_left")
        self.state.engines[2] = EngineState(engine_index=2, engine_id="engine_right")

    def step_intake(
        self,
        engine_index: int,
        engine_rpm: float,
        throttle_percent: float,
        ambient_pressure_pa: float,
        ambient_temp_k: float,
        manifold_pressure_pa: Optional[float] = None,
        engine_config: Optional[Dict[str, Any]] = None
    ) -> EngineState:
        """
        Executes one deterministic intake physics integration step for a specific engine instance.
        If manifold_pressure_pa is supplied (from Phase 3.4 TurboRunner closed-loop dynamics),
        it is used directly to compute intake air density and airflow.
        Modifying Engine 1 NEVER modifies Engine 2 state.
        """
        if engine_index not in self.state.engines:
            self.state.engines[engine_index] = EngineState(
                engine_index=engine_index,
                engine_id=f"engine_{engine_index}"
            )

        eng = self.state.engines[engine_index]
        cfg = engine_config if engine_config is not None else self.engine_config

        # Extract configuration values strictly via ConfigLoader schema
        v_d = cfg["geometry_and_inertia"]["displacement_m3"]["value"]
        rated_rpm = cfg["power_and_performance"]["rated_rpm"]["value"]
        p_max_map = cfg["turbocharger"]["max_manifold_absolute_pressure_pa"]["value"]
        pi_max = cfg["turbocharger"]["max_compressor_pressure_ratio"]["value"]
        eta_c = cfg["turbocharger"]["compressor_efficiency_peak"]["value"]
        n_tmax = cfg["turbocharger"]["max_turbo_speed_rpm"]["value"]

        # Validate inputs
        IntakeTurbochargerModel.validate_inputs(
            ambient_pressure_pa=ambient_pressure_pa,
            ambient_temp_k=ambient_temp_k,
            engine_rpm=engine_rpm,
            displacement_m3=v_d
        )

        # 1. Determine Manifold Absolute Pressure (MAP)
        if manifold_pressure_pa is not None:
            p_map = float(manifold_pressure_pa)
            pi_c = p_map / ambient_pressure_pa if ambient_pressure_pa > 0 else 1.0
        elif eng.manifold_pressure_pa > 0 and eng.manifold_pressure_pa != 101325.0:
            p_map = eng.manifold_pressure_pa
            pi_c = p_map / ambient_pressure_pa if ambient_pressure_pa > 0 else 1.0
        else:
            p_map, pi_c = IntakeTurbochargerModel.compute_manifold_absolute_pressure(
                ambient_pressure_pa=ambient_pressure_pa,
                throttle_percent=throttle_percent,
                max_map_pa=p_max_map,
                max_pressure_ratio=pi_max
            )

        # 2. Gauge Boost Pressure
        p_gauge = IntakeTurbochargerModel.compute_gauge_boost_pressure(
            manifold_absolute_pressure_pa=p_map,
            ambient_pressure_pa=ambient_pressure_pa
        )

        # 3. Compressor Outlet Temperature
        t_comp_out = IntakeTurbochargerModel.compute_compressor_outlet_temperature(
            ambient_temp_k=ambient_temp_k,
            compressor_pressure_ratio=pi_c,
            compressor_efficiency=eta_c
        )

        # 4. Intake Air Density
        rho_in = IntakeTurbochargerModel.compute_intake_air_density(
            manifold_absolute_pressure_pa=p_map,
            intake_temp_k=t_comp_out
        )

        # 5. Volumetric Efficiency
        eta_v = IntakeTurbochargerModel.compute_volumetric_efficiency(
            engine_rpm=engine_rpm,
            manifold_absolute_pressure_pa=p_map,
            rated_rpm=rated_rpm
        )

        # 6. Engine Air Mass Flow Rate
        m_dot_kg_s, m_dot_kg_h = IntakeTurbochargerModel.compute_engine_air_mass_flow(
            engine_rpm=engine_rpm,
            intake_air_density_kg_m3=rho_in,
            displacement_m3=v_d,
            volumetric_efficiency=eta_v
        )

        # Standalone backward compatibility fallback for Phase 3.2 tests
        if eng.turbocharger.turbo_speed_rpm == 0.0:
            n_turbo_fallback = IntakeTurbochargerModel.compute_turbo_shaft_speed(
                engine_rpm=engine_rpm,
                throttle_percent=throttle_percent,
                rated_engine_rpm=rated_rpm,
                max_turbo_rpm=n_tmax
            )
            eng.turbocharger.turbo_speed_rpm = n_turbo_fallback

        # Update Engine State Subsystem Container
        eng.manifold_pressure_pa = p_map
        eng.air_mass_flow_kg_s = m_dot_kg_s

        eng.turbocharger.compressor_pressure_ratio = pi_c
        eng.turbocharger.max_manifold_absolute_pressure_pa = p_max_map
        eng.turbocharger.compressor_efficiency = eta_c

        return eng
